#imagem do mysql
FROM mysql:8.0

# Copie o arquivo de banco de dados (caso necessário)
COPY ./site/cadastroDB.sql /docker-entrypoint-initdb.d/

# Defina as variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=meubanco

# Exponha a porta padrão do MySQL
EXPOSE 3307
